name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps

      - uses: nrwl/nx-set-shas@v4

      - name: Lint, test, and build (affected)
        run: yarn nx affected -t lint test build e2e

      - name: Typecheck
        run: yarn typecheck

      - name: Build npm library
        run: yarn build:lib
